import Head from "next/head";
import React from 'react'
import Main from "../components/Main.jsx"





export default function Home() {
  return (
    <div>
      <Head>
        <title> AKASH | Front-End Developer</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon" href="/../public/My project fav.ico" />
      </Head>
    <Main/>
    </div>
  );
}
